from typing import Callable, Protocol


class OnlyXtDataProtocol(Protocol):
    def get_market_data_ex(
        self, fields: list[str], stock_list: list[str], period: str, **kwargs: object
    ) -> dict[str, object]: ...
    def subscribe_quote(
        self,
        stock_code: str,
        period: str = "tick",
        callback: Callable[..., None] | None = None,
    ) -> int: ...
    def unsubscribe_quote(self, seq: int) -> None: ...
    def get_instrument_detail(self, stock_code: str) -> dict[str, object] | None: ...
    def get_trading_calendar(self, market: str, **kwargs: object) -> list[str]: ...


class OnlyXtTraderProtocol(Protocol):
    def register_callback(self, callback: object) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def connect(self) -> int: ...
    def subscribe(self, account: object) -> int: ...
