"""Stable Strategy Ledger enumerations."""

from enum import StrEnum


class OnlyStrategyLedgerStatus(StrEnum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    RECONCILING = "RECONCILING"
    SUSPENDED = "SUSPENDED"
    CLOSED = "CLOSED"
    ERROR = "ERROR"


class OnlyStrategyCapitalAllocationMode(StrEnum):
    FIXED_CAPITAL = "FIXED_CAPITAL"
    EQUITY_PERCENTAGE = "EQUITY_PERCENTAGE"
    SHARED_POOL = "SHARED_POOL"


class OnlyStrategyCashEntryType(StrEnum):
    INITIAL_ALLOCATION = "INITIAL_ALLOCATION"
    ORDER_RESERVATION = "ORDER_RESERVATION"
    ORDER_RESERVATION_RELEASE = "ORDER_RESERVATION_RELEASE"
    BUY_SETTLEMENT = "BUY_SETTLEMENT"
    SELL_SETTLEMENT = "SELL_SETTLEMENT"
    FEE = "FEE"
    EXTERNAL_DEPOSIT = "EXTERNAL_DEPOSIT"
    EXTERNAL_WITHDRAWAL = "EXTERNAL_WITHDRAWAL"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"


class OnlyStrategyFeeType(StrEnum):
    COMMISSION = "COMMISSION"
    EXCHANGE_FEE = "EXCHANGE_FEE"
    STAMP_DUTY = "STAMP_DUTY"
    TRANSFER_FEE = "TRANSFER_FEE"
    REGULATORY_FEE = "REGULATORY_FEE"
    BROKER_FEE = "BROKER_FEE"
    BORROW_FEE = "BORROW_FEE"
    FINANCING_INTEREST = "FINANCING_INTEREST"
    FUNDING_FEE = "FUNDING_FEE"
    OTHER = "OTHER"


class OnlyStrategyCashReservationState(StrEnum):
    ACTIVE = "ACTIVE"
    PARTIALLY_CONSUMED = "PARTIALLY_CONSUMED"
    CONSUMED = "CONSUMED"
    RELEASED = "RELEASED"
    FAILED = "FAILED"


class OnlyStrategyCashReservationStage(StrEnum):
    LOCAL_ONLY = "LOCAL_ONLY"
    SENT_TO_BROKER = "SENT_TO_BROKER"
    BROKER_ACKNOWLEDGED = "BROKER_ACKNOWLEDGED"
    RELEASE_PENDING = "RELEASE_PENDING"
    RELEASED = "RELEASED"


class OnlyStrategyReturnMethod(StrEnum):
    SIMPLE_RETURN = "SIMPLE_RETURN"
    TIME_WEIGHTED_RETURN = "TIME_WEIGHTED_RETURN"
    MONEY_WEIGHTED_RETURN = "MONEY_WEIGHTED_RETURN"


class OnlyStrategyLedgerMutationStatus(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    STALE = "STALE"
    NO_CHANGE = "NO_CHANGE"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class OnlyStrategyLedgerReplayOperation(StrEnum):
    CREATE = "CREATE"
    ACTIVATE = "ACTIVATE"
    RESERVE_CASH = "RESERVE_CASH"
    RELEASE_CASH = "RELEASE_CASH"
    APPLY_TRADE = "APPLY_TRADE"
    APPLY_FEE = "APPLY_FEE"
    APPLY_EXTERNAL_CASH_FLOW = "APPLY_EXTERNAL_CASH_FLOW"
    APPLY_VALUATION = "APPLY_VALUATION"
    CLOSE = "CLOSE"
