# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: onlyalpha_gateway_protocol/v1/error.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'onlyalpha_gateway_protocol/v1/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)onlyalpha_gateway_protocol/v1/error.proto\x12\x14onlyalpha.gateway.v1\"\x86\x01\n\x0cGatewayError\x12\x34\n\x04\x63ode\x18\x01 \x01(\x0e\x32&.onlyalpha.gateway.v1.GatewayErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rprovider_code\x18\x03 \x01(\t\x12\x18\n\x10provider_message\x18\x04 \x01(\t*\x94\x02\n\x10GatewayErrorCode\x12\"\n\x1eGATEWAY_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x13\n\x0fINVALID_REQUEST\x10\x01\x12\x15\n\x11PROTOCOL_MISMATCH\x10\x02\x12\x1a\n\x16UNSUPPORTED_CAPABILITY\x10\x03\x12\r\n\tNOT_READY\x10\x04\x12\x14\n\x10\x43OMMAND_CONFLICT\x10\x05\x12\x18\n\x14PROVIDER_UNAVAILABLE\x10\x06\x12\x15\n\x11PROVIDER_REJECTED\x10\x07\x12\x15\n\x11\x44\x45\x41\x44LINE_EXCEEDED\x10\x08\x12\x13\n\x0fRESYNC_REQUIRED\x10\t\x12\x12\n\x0eINTERNAL_ERROR\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onlyalpha_gateway_protocol.v1.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GATEWAYERRORCODE']._serialized_start=205
  _globals['_GATEWAYERRORCODE']._serialized_end=481
  _globals['_GATEWAYERROR']._serialized_start=68
  _globals['_GATEWAYERROR']._serialized_end=202
# @@protoc_insertion_point(module_scope)
