# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from onlyalpha_gateway_protocol.v1 import gateway_pb2 as onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in onlyalpha_gateway_protocol/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/onlyalpha.gateway.v1.GatewayService/Handshake',
                request_serializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.ApplyTestMutation = channel.unary_unary(
                '/onlyalpha.gateway.v1.GatewayService/ApplyTestMutation',
                request_serializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.ApplyTestMutationRequest.SerializeToString,
                response_deserializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.ApplyTestMutationResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyTestMutation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.HandshakeRequest.FromString,
                    response_serializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.HandshakeResponse.SerializeToString,
            ),
            'ApplyTestMutation': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyTestMutation,
                    request_deserializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.ApplyTestMutationRequest.FromString,
                    response_serializer=onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.ApplyTestMutationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onlyalpha.gateway.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('onlyalpha.gateway.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onlyalpha.gateway.v1.GatewayService/Handshake',
            onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.HandshakeRequest.SerializeToString,
            onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyTestMutation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onlyalpha.gateway.v1.GatewayService/ApplyTestMutation',
            onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.ApplyTestMutationRequest.SerializeToString,
            onlyalpha__gateway__protocol_dot_v1_dot_gateway__pb2.ApplyTestMutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
