# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: onlyalpha_gateway_protocol/v1/identity.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'onlyalpha_gateway_protocol/v1/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,onlyalpha_gateway_protocol/v1/identity.proto\x12\x14onlyalpha.gateway.v1\"B\n\x0fGatewayIdentity\x12\x12\n\ngateway_id\x18\x01 \x01(\t\x12\x1b\n\x13gateway_instance_id\x18\x02 \x01(\t\"`\n\x15RemoteCommandIdentity\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x1b\n\x13\x63ommand_fingerprint\x18\x02 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onlyalpha_gateway_protocol.v1.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GATEWAYIDENTITY']._serialized_start=70
  _globals['_GATEWAYIDENTITY']._serialized_end=136
  _globals['_REMOTECOMMANDIDENTITY']._serialized_start=138
  _globals['_REMOTECOMMANDIDENTITY']._serialized_end=234
# @@protoc_insertion_point(module_scope)
