# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from onlyalpha_gateway_protocol.v1 import stream_pb2 as onlyalpha__gateway__protocol_dot_v1_dot_stream__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in onlyalpha_gateway_protocol/v1/stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchTestEvents = channel.unary_stream(
                '/onlyalpha.gateway.v1.GatewayStreamService/WatchTestEvents',
                request_serializer=onlyalpha__gateway__protocol_dot_v1_dot_stream__pb2.WatchTestEventsRequest.SerializeToString,
                response_deserializer=onlyalpha__gateway__protocol_dot_v1_dot_stream__pb2.TestStreamItem.FromString,
                _registered_method=True)


class GatewayStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WatchTestEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchTestEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTestEvents,
                    request_deserializer=onlyalpha__gateway__protocol_dot_v1_dot_stream__pb2.WatchTestEventsRequest.FromString,
                    response_serializer=onlyalpha__gateway__protocol_dot_v1_dot_stream__pb2.TestStreamItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onlyalpha.gateway.v1.GatewayStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('onlyalpha.gateway.v1.GatewayStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WatchTestEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/onlyalpha.gateway.v1.GatewayStreamService/WatchTestEvents',
            onlyalpha__gateway__protocol_dot_v1_dot_stream__pb2.WatchTestEventsRequest.SerializeToString,
            onlyalpha__gateway__protocol_dot_v1_dot_stream__pb2.TestStreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
