"""Stable worker process exit codes."""

SUCCESS = 0
INVALID_REQUEST = 10
SDK_IMPORT_FAILED = 11
CLIENT_NOT_READY = 12
DOWNLOAD_FAILED = 13
QUERY_FAILED = 14
EMPTY_RESULT = 15
DATA_VALIDATION_FAILED = 16
RESULT_SERIALIZATION_FAILED = 17
PROTOCOL_ERROR = 18
TIMEOUT = 21
PROTOCOL_VERSION_MISMATCH = 22
