"""Execution update processing states and failure taxonomy."""

from enum import StrEnum


class OnlyExecutionProcessingStatus(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    STALE = "STALE"
    IGNORED = "IGNORED"
    REJECTED = "REJECTED"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    FAILED = "FAILED"


class OnlyExecutionFailureCode(StrEnum):
    SCOPE_MISMATCH = "SCOPE_MISMATCH"
    UNKNOWN_GATEWAY = "UNKNOWN_GATEWAY"
    UNKNOWN_ACCOUNT = "UNKNOWN_ACCOUNT"
    UNKNOWN_ORDER = "UNKNOWN_ORDER"
    UNSUPPORTED_UPDATE_TYPE = "UNSUPPORTED_UPDATE_TYPE"
    INVALID_UPDATE = "INVALID_UPDATE"
    ORDER_CONFLICT = "ORDER_CONFLICT"
    OUT_OF_ORDER_TRADE = "OUT_OF_ORDER_TRADE"
    RESERVATION_INSUFFICIENT = "RESERVATION_INSUFFICIENT"
    INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
    DEPENDENCY_FAILURE = "DEPENDENCY_FAILURE"


class OnlyExecutionMutationStatus(StrEnum):
    PLANNED = "PLANNED"
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


class OnlyExecutionMutationStep(StrEnum):
    VALIDATION = "VALIDATION"
    ORDER = "ORDER"
    POSITION = "POSITION"
    ALLOCATION = "ALLOCATION"
    SETTLEMENT = "SETTLEMENT"
    MARGIN = "MARGIN"
    FEE = "FEE"
    STRATEGY_LEDGER = "STRATEGY_LEDGER"
    ACCOUNT = "ACCOUNT"
    RESERVATION = "RESERVATION"
    RISK = "RISK"
    INVARIANT_CHECK = "INVARIANT_CHECK"
    EVENT = "EVENT"
