"""Governance gate: golden recovery baselines are never regenerated by lanes or CI."""

from __future__ import annotations

from pathlib import Path

import pytest

pytestmark = pytest.mark.architecture

ROOT = Path(__file__).resolve().parents[2]


def test_golden_recovery_baselines_are_not_regenerated_by_automation() -> None:
    # Allowlist rationale:
    # - tests/support/recovery_baselines.py only NAMES the script inside the fail-closed
    #   identity-mismatch error hint; it never invokes it.
    # - tests/architecture/test_product_surface_boundaries.py only NAMES the script in a
    #   product-surface boundary table (labeling it "TEST TOOLING"); it never invokes it.
    # - this gate file necessarily contains the literal string it scans for.
    # The gate FAILS if scripts/test_suite.py, scripts/verify.py or any .github/workflows
    # file ever references the script, i.e. if a canonical lane or CI ever invokes it.
    callers = {
        str(path.relative_to(ROOT))
        for root in (ROOT / ".github/workflows", ROOT / "scripts", ROOT / "tests")
        for path in root.rglob("*")
        if path.suffix in {".py", ".yml", ".yaml", ".sh"}
        and "regenerate_recovery_baselines" in path.read_text(encoding="utf-8")
    }
    assert callers <= {
        "tests/architecture/test_recovery_baseline_governance.py",
        "tests/support/recovery_baselines.py",
        "tests/architecture/test_product_surface_boundaries.py",
    }


def test_recovery_identity_guard_remains_fail_closed() -> None:
    source = (ROOT / "tests/support/recovery_baselines.py").read_text(encoding="utf-8")
    assert "RECOVERY_BASELINE_STRATEGY_IDENTITY_MISMATCH" in source


def test_baseline_changes_require_documented_recertification() -> None:
    doc = (ROOT / "docs/testing.md").read_text(encoding="utf-8")
    assert "docs/audits/" in doc and "justification" in doc.lower()
