import ast
from pathlib import Path

from onlyalpha_http_server.market_data.stream_schema import MarketDataSubscribedDto

ROOT = Path(__file__).parents[2]


def test_stream_contract_has_one_generator_and_two_transport_projections() -> None:
    generator = (ROOT / "scripts/market_data_stream_contract.py").read_text(encoding="utf-8")
    assert "MarketDataStreamSubscribeDto.model_json_schema()" in generator
    assert "market_data_stream_event_adapter.json_schema()" in generator
    assert (ROOT / "contracts/product-api/v2/market-data-stream.schema.json").is_file()
    web = ROOT / "packages/onlyalpha-web-console/src/api/marketData/stream.generated.ts"
    assert web.read_text(encoding="utf-8").startswith("// Generated by scripts/market_data_stream_contract.py")


def test_browser_uses_product_cursor_and_target_acquisition_without_resolution_branch() -> None:
    source = (ROOT / "packages/onlyalpha-web-console/src/features/workspace/useMarketDataChart.ts").read_text(
        encoding="utf-8"
    )
    assert "historicalCursor" not in source
    assert "endNs /" not in source
    assert "bar_semantic: marketDataBarSemantic(1)" not in source
    assert "client.createAcquisition(active, query)" in source
    assert '"PROVIDER_NATIVE"' not in source and '"DERIVED"' not in source
    workspace = (ROOT / "packages/onlyalpha-web-console/src/features/workspace/WorkspacePage.tsx").read_text(
        encoding="utf-8"
    )
    assert "derived_supported" not in source + workspace


def test_subscribed_emission_matches_server_contract_fields() -> None:
    source = (ROOT / "src/onlyalpha/application/market_data_stream.py").read_text(encoding="utf-8")
    event_calls = (
        node
        for node in ast.walk(ast.parse(source))
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "OnlyMarketDataStreamEventV1"
        and node.args
        and isinstance(node.args[0], ast.Constant)
        and node.args[0].value == "SUBSCRIBED"
    )
    [subscribed] = list(event_calls)
    payload = subscribed.args[1]
    assert isinstance(payload, ast.Dict)
    keys = {key.value for key in payload.keys if isinstance(key, ast.Constant)}
    assert keys == set(MarketDataSubscribedDto.model_fields) - {"schema_version", "event"}
