from pathlib import Path

from onlyalpha_http_server.market_data.schema import MarketDataBarWindowDto

ROOT = Path(__file__).parents[2]


def test_http_bars_contract_has_one_server_authority_and_generated_browser_projection() -> None:
    generator = (ROOT / "scripts/market_data_http_contract.py").read_text(encoding="utf-8")
    assert "MarketDataBarWindowDto.model_json_schema()" in generator
    web = ROOT / "packages/onlyalpha-web-console/src/api/marketData/http.generated.ts"
    generated = web.read_text(encoding="utf-8")
    assert generated.startswith("// Generated by scripts/market_data_http_contract.py")
    assert set(MarketDataBarWindowDto.model_fields) == {
        line.strip().split(":", 1)[0]
        for line in generated.split("export const marketDataBarsSchema =", 1)[1].split(".refine", 1)[0].splitlines()
        if line.startswith("        ") and ":" in line
    }


def test_http_contract_freshness_is_in_static_and_ci_lanes() -> None:
    script = "scripts/market_data_http_contract.py"
    assert script in (ROOT / "scripts/web_suite.py").read_text(encoding="utf-8")
    assert f"{script} check" in (ROOT / ".github/workflows/quality.yml").read_text(encoding="utf-8")
