/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/research/artifacts/{research_result_fingerprint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Summary */
        get: operations["artifact_summary_api_v2_research_artifacts__research_result_fingerprint__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistics Catalog */
        get: operations["statistics_catalog_api_v2_research_artifacts__research_result_fingerprint__statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/statistics/{statistics_fingerprint}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistic Series */
        get: operations["statistic_series_api_v2_research_artifacts__research_result_fingerprint__statistics__statistics_fingerprint__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ResearchArtifactSummaryDto */
        ResearchArtifactSummaryDto: {
            /** Artifact Content Fingerprint */
            artifact_content_fingerprint: string;
            /** Artifact Profile */
            artifact_profile: string;
            /** Artifact Schema Version */
            artifact_schema_version: number;
            /** Created At */
            created_at: string;
            /** Dataset Snapshot Fingerprint */
            dataset_snapshot_fingerprint: string;
            /** Research Result Content Fingerprint */
            research_result_content_fingerprint: string;
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /** Research Result Plan Fingerprint */
            research_result_plan_fingerprint: string;
            /** Research Result Schema Version */
            research_result_schema_version: number;
            /** Row Count */
            row_count: number;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Statistics Count */
            statistics_count: number;
        };
        /** ResearchErrorDto */
        ResearchErrorDto: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchNumericDefinitionDto */
        ResearchNumericDefinitionDto: {
            /** Output Quantum */
            output_quantum: string;
            /** Precision */
            precision: number;
            /** Representation */
            representation: string;
            /** Rounding */
            rounding: string;
        };
        /** ResearchSeriesReferenceDto */
        ResearchSeriesReferenceDto: {
            /** Calculation Fingerprint */
            calculation_fingerprint: string;
            /** Node Fingerprint */
            node_fingerprint: string;
            /** Output Name */
            output_name: string;
        };
        /** ResearchStatisticPointDto */
        ResearchStatisticPointDto: {
            /** Sample Count */
            sample_count: number;
            /** Statistic Value */
            statistic_value: string | null;
            /** Status */
            status: string;
            /** Ts Event Ns */
            ts_event_ns: string;
        };
        /** ResearchStatisticSeriesPageDto */
        ResearchStatisticSeriesPageDto: {
            /** Has More */
            has_more: boolean;
            /** Next After Ts Event Ns */
            next_after_ts_event_ns: string | null;
            /** Points */
            points: components["schemas"]["ResearchStatisticPointDto"][];
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Statistics Fingerprint */
            statistics_fingerprint: string;
        };
        /** ResearchStatisticsCatalogDto */
        ResearchStatisticsCatalogDto: {
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Statistics */
            statistics: components["schemas"]["ResearchStatisticsDescriptorDto"][];
        };
        /** ResearchStatisticsDefinitionDto */
        ResearchStatisticsDefinitionDto: {
            /** Method */
            method: string;
            /** Minimum Observations */
            minimum_observations: number;
            numeric: components["schemas"]["ResearchNumericDefinitionDto"];
            /** Pairing Policy */
            pairing_policy: string;
            /** Rank Tie Method */
            rank_tie_method: string;
            /** Universe Policy */
            universe_policy: string;
            /** Weighting */
            weighting: string;
        };
        /** ResearchStatisticsDescriptorDto */
        ResearchStatisticsDescriptorDto: {
            definition: components["schemas"]["ResearchStatisticsDefinitionDto"];
            feature: components["schemas"]["ResearchSeriesReferenceDto"];
            /** Result Content Fingerprint */
            result_content_fingerprint: string;
            /** Row Count */
            row_count: number;
            /** Statistics Fingerprint */
            statistics_fingerprint: string;
            /** Statistics Result Fingerprint */
            statistics_result_fingerprint: string;
            /** Statistics Result Schema Version */
            statistics_result_schema_version: number;
            target: components["schemas"]["ResearchSeriesReferenceDto"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifact_summary_api_v2_research_artifacts__research_result_fingerprint__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_result_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchArtifactSummaryDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    statistics_catalog_api_v2_research_artifacts__research_result_fingerprint__statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_result_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchStatisticsCatalogDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    statistic_series_api_v2_research_artifacts__research_result_fingerprint__statistics__statistics_fingerprint__series_get: {
        parameters: {
            query?: {
                from_ts_event_ns?: string | null;
                to_ts_event_ns?: string | null;
                after_ts_event_ns?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                research_result_fingerprint: string;
                statistics_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchStatisticSeriesPageDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
}
