// Generated by scripts/market_data_http_contract.py; do not edit.
import { z } from "zod";

const MarketDataBarDtoSchema = z.strictObject({
    bar_start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    bar_end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    open: z.string(),
    high: z.string(),
    low: z.string(),
    close: z.string(),
    volume: z.string(),
    closed: z.boolean()
});
const MarketDataCalendarPeriodFormationDtoSchema = z.strictObject({
    schema_version: z.literal(1),
    kind: z.literal("CALENDAR_PERIOD"),
    unit: z.enum(["DAY", "WEEK", "MONTH"]),
    count: z.number().int().min(1),
    alignment: z.enum(["UTC", "SESSION_START"])
});
const MarketDataCoverageGapDtoSchema = z.strictObject({
    start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$"))
});
const MarketDataFixedDurationFormationDtoSchema = z.strictObject({
    schema_version: z.literal(1),
    kind: z.literal("FIXED_DURATION"),
    window_minutes: z.number().int().min(1),
    stride_minutes: z.number().int().min(1),
    alignment: z.enum(["UTC", "SESSION_START"])
});
const MarketDataRevisionEvidenceDtoSchema = z.strictObject({
    revision_id: z.string().min(1),
    revision_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    manifest_id: z.string().min(1),
    manifest_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    seal_id: z.string().min(1),
    covered_start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    covered_end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$"))
});
const MarketDataSourceSelectionDtoSchema = z.strictObject({
    integration_id: z.string().min(1),
    integration_revision_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    type_id: z.string().min(1),
    source_id: z.string().min(1),
    environment: z.string().min(1)
});
const MarketDataTickCountFormationDtoSchema = z.strictObject({
    schema_version: z.literal(1),
    kind: z.literal("TICK_COUNT"),
    count: z.number().int().min(1)
});
const MarketDataValueFormationDtoSchema = z.strictObject({
    schema_version: z.literal(1),
    kind: z.literal("VALUE"),
    value: z.string().regex(new RegExp("^[0-9]+(?:\\.[0-9]+)?$"))
});
const MarketDataVolumeFormationDtoSchema = z.strictObject({
    schema_version: z.literal(1),
    kind: z.literal("VOLUME"),
    quantity: z.string().regex(new RegExp("^[0-9]+(?:\\.[0-9]+)?$"))
});
const OnlyPriceTypeSchema = z.enum(["LAST", "BID", "ASK", "MID", "MARK"]);
const MarketDataBarSemanticDtoSchema = z.strictObject({
    schema_version: z.literal(2),
    formation: z.union([
        MarketDataFixedDurationFormationDtoSchema,
        MarketDataCalendarPeriodFormationDtoSchema,
        MarketDataTickCountFormationDtoSchema,
        MarketDataVolumeFormationDtoSchema,
        MarketDataValueFormationDtoSchema
    ]),
    price_type: OnlyPriceTypeSchema,
    adjustment_policy: z.enum(["RAW", "FORWARD", "BACKWARD"])
});
const MarketDataCoverageDtoSchema = z.strictObject({
    status: z.enum(["COMPLETE", "INCOMPLETE", "UNPROVABLE"]),
    manifest_id: z.string().nullable(),
    manifest_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
    expected_bar_count: z.number().int(),
    actual_bar_count: z.number().int(),
    issues: z.array(z.string()),
    gaps: z.array(MarketDataCoverageGapDtoSchema),
    planned_acquisition_ranges: z.array(MarketDataCoverageGapDtoSchema)
});
export const marketDataBarsSchema = z
    .strictObject({
        schema_version: z.literal(1),
        source_selection: MarketDataSourceSelectionDtoSchema,
        instrument_id: z.string(),
        display_symbol: z.string(),
        venue: z.string(),
        market: z.string(),
        bar_semantic: MarketDataBarSemanticDtoSchema,
        closed_only: z.boolean(),
        anchor_kind: z.enum(["LATEST_CLOSED", "BEFORE_TIME"]),
        requested_before_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")).nullable(),
        requested_bar_count: z.number().int().min(1),
        resolved_start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
        resolved_end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
        coverage: MarketDataCoverageDtoSchema,
        bars: z.array(MarketDataBarDtoSchema),
        revision_evidence: z.array(MarketDataRevisionEvidenceDtoSchema),
        history_projection_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        derived_projection_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        aggregation_semantics_version: z.string().nullable(),
        calendar_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        resolution_mode: z.enum(["PROVIDER_NATIVE", "DERIVED"]).nullable(),
        resolution_plan_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        resume_after_sequence: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")).nullable(),
        resume_plan_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable()
    })
    .refine((value) => {
        const complete = value.coverage.status === "COMPLETE";
        const derived = value.resolution_mode === "DERIVED";
        return (
            value.bars.length > 0 === complete &&
            (!complete || value.revision_evidence.length > 0) &&
            (value.history_projection_fingerprint !== null) === complete &&
            (value.resume_after_sequence !== null) === complete &&
            (value.resume_plan_fingerprint !== null) === complete &&
            (value.derived_projection_fingerprint !== null) === (complete && derived)
        );
    });
export type MarketDataBars = z.infer<typeof marketDataBarsSchema>;
