// Generated by scripts/market_data_http_contract.py; do not edit.
import { z } from "zod";

const MarketDataBarDtoSchema = z.strictObject({
    bar_start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    bar_end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    open: z.string(),
    high: z.string(),
    low: z.string(),
    close: z.string(),
    volume: z.string(),
    closed: z.boolean()
});
const MarketDataBarSpecificationDtoSchema = z.strictObject({
    aggregation: z.literal("TIME"),
    step: z.number().int().min(1).max(240),
    price_type: z.literal("LAST")
});
const MarketDataCoverageGapDtoSchema = z.strictObject({
    start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$"))
});
const MarketDataSourceSelectionDtoSchema = z.strictObject({
    integration_id: z.string().min(1),
    integration_revision_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    type_id: z.string().min(1),
    source_id: z.string().min(1),
    environment: z.string().min(1)
});
const MarketDataCoverageDtoSchema = z.strictObject({
    status: z.enum(["COMPLETE", "INCOMPLETE", "UNPROVABLE"]),
    manifest_id: z.string().nullable(),
    manifest_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
    expected_bar_count: z.number().int(),
    actual_bar_count: z.number().int(),
    issues: z.array(z.string()),
    gaps: z.array(MarketDataCoverageGapDtoSchema),
    planned_acquisition_ranges: z.array(MarketDataCoverageGapDtoSchema)
});
export const marketDataBarsSchema = z
    .strictObject({
        schema_version: z.literal(1),
        source_selection: MarketDataSourceSelectionDtoSchema,
        instrument_id: z.string(),
        display_symbol: z.string(),
        venue: z.string(),
        market: z.string(),
        bar_specification: MarketDataBarSpecificationDtoSchema,
        aggregation_source: z.enum(["EXTERNAL", "INTERNAL"]),
        adjustment: z.literal("RAW"),
        closed_only: z.boolean(),
        start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
        end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
        coverage: MarketDataCoverageDtoSchema,
        revision_id: z.string().nullable(),
        revision_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        seal_id: z.string().nullable(),
        bars: z.array(MarketDataBarDtoSchema),
        aggregation_semantics_version: z.string().nullable(),
        calendar_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        resolution_mode: z.enum(["EXTERNAL_NATIVE", "INTERNAL_DERIVED"]).nullable(),
        resolution_plan_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        base_revision_id: z.string().nullable(),
        construction_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable(),
        resume_after_sequence: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")).nullable(),
        resume_plan_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable()
    })
    .refine((value) => {
        const complete = value.coverage.status === "COMPLETE";
        return (
            (value.resume_after_sequence !== null) === complete &&
            (value.resume_plan_fingerprint !== null) === complete
        );
    });
export type MarketDataBars = z.infer<typeof marketDataBarsSchema>;
