// Generated by scripts/market_data_stream_contract.py; do not edit.
import { z } from "zod";

const MarketDataBarSpecificationDtoSchema = z.strictObject({
    aggregation: z.literal("TIME"),
    step: z.number().int().min(1).max(240),
    price_type: z.literal("LAST")
});
const MarketDataStreamSourceReferenceDtoSchema = z.strictObject({
    integration_id: z.string().min(1),
    integration_revision_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    expected_type_id: z.string().min(1)
});
const MarketDataBarDtoSchema = z.strictObject({
    bar_start_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    bar_end_ns: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
    open: z.string(),
    high: z.string(),
    low: z.string(),
    close: z.string(),
    volume: z.string(),
    closed: z.boolean()
});
const MarketDataBaseCursorDtoSchema = z.strictObject({
    schema_version: z.literal(2),
    event: z.literal("BASE_CURSOR"),
    sequence: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$"))
});
const MarketDataStateDtoSchema = z.strictObject({
    schema_version: z.literal(2),
    event: z.literal("STATE"),
    state: z.enum(["CONNECTING", "RECOVERING", "READY", "DEGRADED", "FAILED", "CLOSED"])
});
const MarketDataStreamErrorDtoSchema = z.strictObject({
    schema_version: z.literal(2),
    event: z.literal("ERROR"),
    code: z.string(),
    detail: z.string().nullable().optional()
});
const MarketDataSubscribedDtoSchema = z.strictObject({
    schema_version: z.literal(2),
    event: z.literal("SUBSCRIBED"),
    stream_id: z.string(),
    source_id: z.string(),
    instrument_id: z.string(),
    resolution_mode: z.enum(["EXTERNAL_NATIVE", "INTERNAL_DERIVED"]),
    resolution_plan_fingerprint: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    cursor_bar_step_minutes: z.number().int().min(1).max(240)
});
const MarketDataBarClosedDtoSchema = z.strictObject({
    schema_version: z.literal(2),
    source_id: z.string(),
    instrument_id: z.string(),
    bar_specification: MarketDataBarSpecificationDtoSchema,
    bar: MarketDataBarDtoSchema,
    event: z.literal("BAR_CLOSED"),
    sequence: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$"))
});
const MarketDataBarPreviewDtoSchema = z.strictObject({
    schema_version: z.literal(2),
    source_id: z.string(),
    instrument_id: z.string(),
    bar_specification: MarketDataBarSpecificationDtoSchema,
    bar: MarketDataBarDtoSchema,
    event: z.literal("BAR_PREVIEW")
});
export const marketDataStreamSubscribeSchema = z
    .strictObject({
        schema_version: z.literal(2),
        operation: z.literal("SUBSCRIBE_BAR"),
        source_reference: MarketDataStreamSourceReferenceDtoSchema,
        instrument_id: z.string().min(1),
        bar_specification: MarketDataBarSpecificationDtoSchema,
        resume_after_sequence: z.string().regex(new RegExp("^(?:0|[1-9][0-9]*)$")),
        resume_plan_fingerprint: z
            .string()
            .regex(new RegExp("^[0-9a-f]{64}$"))
            .nullable()
            .optional()
    })
    .refine(
        (value) =>
            value.resume_after_sequence === "0" ||
            (value.resume_plan_fingerprint !== null && value.resume_plan_fingerprint !== undefined)
    );
export const marketDataStreamEventSchema = z.union([
    MarketDataSubscribedDtoSchema,
    MarketDataStateDtoSchema,
    MarketDataBaseCursorDtoSchema,
    MarketDataBarPreviewDtoSchema,
    MarketDataBarClosedDtoSchema,
    MarketDataStreamErrorDtoSchema
]);
export type MarketDataStreamSubscribe = z.infer<typeof marketDataStreamSubscribeSchema>;
export type MarketDataStreamEvent = z.infer<typeof marketDataStreamEventSchema>;
