"""Stable Position component enumerations."""

from enum import StrEnum


class OnlyPositionSide(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


class OnlyPositionMode(StrEnum):
    NETTING = "NETTING"
    HEDGING = "HEDGING"


class OnlyPositionStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    RECONCILING = "RECONCILING"
    ERROR = "ERROR"


class OnlySettlementBucket(StrEnum):
    SETTLED = "SETTLED"
    UNSETTLED = "UNSETTLED"
    TODAY = "TODAY"
    YESTERDAY = "YESTERDAY"
    UNKNOWN = "UNKNOWN"


class OnlyAvailabilityState(StrEnum):
    AVAILABLE = "AVAILABLE"
    ORDER_FROZEN = "ORDER_FROZEN"
    RISK_RESERVED = "RISK_RESERVED"
    MARKET_RESTRICTED = "MARKET_RESTRICTED"
    BROKER_RESTRICTED = "BROKER_RESTRICTED"
    CORPORATE_ACTION_LOCKED = "CORPORATE_ACTION_LOCKED"
    RECONCILING = "RECONCILING"


class OnlyPositionRestrictionType(StrEnum):
    UNSETTLED = "UNSETTLED"
    SUSPENDED_INSTRUMENT = "SUSPENDED_INSTRUMENT"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    BROKER_FREEZE = "BROKER_FREEZE"
    COURT_FREEZE = "COURT_FREEZE"
    PLEDGED = "PLEDGED"
    LOCKUP = "LOCKUP"
    BORROW_RECALL = "BORROW_RECALL"
    ACCOUNT_RESTRICTED = "ACCOUNT_RESTRICTED"
    PENDING_TRANSFER = "PENDING_TRANSFER"
    RECONCILING = "RECONCILING"
    UNKNOWN = "UNKNOWN"


class OnlyPositionRestrictionSource(StrEnum):
    LOCAL = "LOCAL"
    MARKET = "MARKET"
    BROKER = "BROKER"
    REGULATOR = "REGULATOR"
    RECONCILIATION = "RECONCILIATION"


class OnlyCostBasisMethod(StrEnum):
    AVERAGE_COST = "AVERAGE_COST"
    FIFO = "FIFO"
    LIFO = "LIFO"
    SPECIFIC_LOT = "SPECIFIC_LOT"


class OnlyPositionFlipPolicy(StrEnum):
    REJECT = "REJECT"
    CLOSE_THEN_OPEN = "CLOSE_THEN_OPEN"
    NET_AUTOMATICALLY = "NET_AUTOMATICALLY"


class OnlyPositionAccessMode(StrEnum):
    CLUSTER_OWNED_ONLY = "CLUSTER_OWNED_ONLY"
    ACCOUNT_SHARED = "ACCOUNT_SHARED"
    RISK_LIQUIDATION = "RISK_LIQUIDATION"
    MANUAL_RECONCILIATION = "MANUAL_RECONCILIATION"


class OnlyPositionMutationStatus(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    STALE = "STALE"
    NO_CHANGE = "NO_CHANGE"


class OnlyPositionReservationStage(StrEnum):
    LOCAL_ONLY = "LOCAL_ONLY"
    SENT_TO_BROKER = "SENT_TO_BROKER"
    BROKER_ACKNOWLEDGED = "BROKER_ACKNOWLEDGED"
    RELEASE_PENDING = "RELEASE_PENDING"
    RELEASED = "RELEASED"


class OnlyPositionReservationState(StrEnum):
    ACTIVE = "ACTIVE"
    PARTIALLY_CONSUMED = "PARTIALLY_CONSUMED"
    CONSUMED = "CONSUMED"
    RELEASED = "RELEASED"
    FAILED = "FAILED"


class OnlyPositionAuthority(StrEnum):
    LOCAL = "LOCAL"
    BROKER = "BROKER"
    DERIVED = "DERIVED"
    RECONCILED = "RECONCILED"


class OnlyReconciliationSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCK_INSTRUMENT = "BLOCK_INSTRUMENT"
    BLOCK_ACCOUNT = "BLOCK_ACCOUNT"
    FAIL_RUNTIME = "FAIL_RUNTIME"


class OnlyReconciliationAction(StrEnum):
    NONE = "NONE"
    RECORD_DIFFERENCE = "RECORD_DIFFERENCE"
    QUERY_ORDERS_AND_TRADES = "QUERY_ORDERS_AND_TRADES"
    BLOCK_INSTRUMENT = "BLOCK_INSTRUMENT"
    BLOCK_ACCOUNT = "BLOCK_ACCOUNT"
    FAIL_RUNTIME = "FAIL_RUNTIME"
