"""Stable storage ports; infrastructure implementations live under persistence."""

from __future__ import annotations

from collections.abc import Mapping
from datetime import datetime
from typing import Protocol

from .models import (
    OnlyCanonicalMarketFactRecord,
    OnlyCoverageManifest,
    OnlyIngestSegment,
    OnlyMarketDataAcquisitionAttempt,
    OnlyMarketDataAcquisitionIntent,
    OnlyMarketDataPhysicalSegmentProof,
    OnlyMarketDataRangeFamily,
    OnlyMarketDataRecordBundle,
    OnlyMarketDataRevision,
    OnlyMarketDataScope,
    OnlyMarketDataSeal,
    OnlyVerifiedSegmentBatch,
)


class OnlyAcquisitionExecutionLease(Protocol):
    @property
    def acquired(self) -> bool: ...
    def close(self) -> None: ...


class OnlyMarketFactStore(Protocol):
    def inspect_segment(self, segment: OnlyIngestSegment) -> str: ...
    def write_segment(self, segment: OnlyIngestSegment, records: tuple[OnlyMarketDataRecordBundle, ...]) -> None: ...
    def verify_segment(self, segment: OnlyIngestSegment, records: tuple[OnlyMarketDataRecordBundle, ...]) -> None: ...
    def write_segments(
        self,
        segments: tuple[OnlyIngestSegment, ...],
        records_by_segment: Mapping[str, tuple[OnlyMarketDataRecordBundle, ...]],
    ) -> None: ...
    def verify_segments(
        self,
        segments: tuple[OnlyIngestSegment, ...],
        records_by_segment: Mapping[str, tuple[OnlyMarketDataRecordBundle, ...]],
        scope: OnlyMarketDataScope | None = None,
    ) -> OnlyVerifiedSegmentBatch: ...
    def read_segment_facts(
        self,
        segments: tuple[OnlyIngestSegment, ...],
        scope: OnlyMarketDataScope,
        proofs: tuple[OnlyMarketDataPhysicalSegmentProof, ...],
    ) -> tuple[OnlyCanonicalMarketFactRecord, ...]: ...


class OnlyMarketDataCatalog(Protocol):
    def commit_durable_segments(
        self, segments: tuple[OnlyIngestSegment, ...], proofs: tuple[OnlyMarketDataPhysicalSegmentProof, ...]
    ) -> None: ...
    def load_physical_proofs(self, segment_ids: tuple[str, ...]) -> tuple[OnlyMarketDataPhysicalSegmentProof, ...]: ...
    def admit_acquisition_intent(self, intent: OnlyMarketDataAcquisitionIntent) -> OnlyMarketDataAcquisitionIntent: ...
    def load_acquisition_intent(self, acquisition_id: str) -> OnlyMarketDataAcquisitionIntent | None: ...
    def start_acquisition_attempt(
        self, acquisition_id: str, *, started_at: datetime
    ) -> OnlyMarketDataAcquisitionAttempt: ...
    def record_acquisition_attempt(self, attempt: OnlyMarketDataAcquisitionAttempt) -> None: ...
    def latest_acquisition_attempt(self, acquisition_id: str) -> OnlyMarketDataAcquisitionAttempt | None: ...
    def try_acquire_acquisition_execution(self, acquisition_id: str) -> OnlyAcquisitionExecutionLease: ...
    def acquisition_execution_active(self, acquisition_id: str) -> bool: ...
    def commit_coverage_manifest(self, manifest: OnlyCoverageManifest) -> None: ...
    def load_coverage_manifest(self, manifest_id: str) -> OnlyCoverageManifest: ...
    def commit_revision(
        self,
        segments: tuple[OnlyIngestSegment, ...],
        manifest: OnlyCoverageManifest,
        revision: OnlyMarketDataRevision,
        seal: OnlyMarketDataSeal,
    ) -> None: ...
    def is_segment_committed(self, segment_id: str, content_hash: str) -> bool: ...
    def segments_committed(self, segments: tuple[OnlyIngestSegment, ...]) -> tuple[bool, ...]: ...
    def load_durable_segments(self, segment_ids: tuple[str, ...]) -> tuple[OnlyIngestSegment, ...]: ...
    def list_durable_segments(self, scope: OnlyMarketDataScope) -> tuple[OnlyIngestSegment, ...]: ...
    def load_sealed_revision(self, revision_id: str) -> tuple[OnlyMarketDataRevision, OnlyMarketDataSeal]: ...
    def sealed_revision_for_manifest(
        self, manifest_id: str
    ) -> tuple[OnlyMarketDataRevision, OnlyMarketDataSeal] | None: ...
    def latest_sealed_revision(self, scope: OnlyMarketDataScope) -> OnlyMarketDataRevision: ...
    def list_current_sealed_revisions_overlapping(
        self, family: OnlyMarketDataRangeFamily, start_ns: int, end_ns: int
    ) -> tuple[OnlyMarketDataRevision, ...]: ...


__all__ = [name for name in globals() if name.startswith("Only")]
