# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: onlyalpha_gateway_protocol/v1/gateway.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'onlyalpha_gateway_protocol/v1/gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from onlyalpha_gateway_protocol.v1 import common_pb2 as onlyalpha__gateway__protocol_dot_v1_dot_common__pb2
from onlyalpha_gateway_protocol.v1 import error_pb2 as onlyalpha__gateway__protocol_dot_v1_dot_error__pb2
from onlyalpha_gateway_protocol.v1 import identity_pb2 as onlyalpha__gateway__protocol_dot_v1_dot_identity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+onlyalpha_gateway_protocol/v1/gateway.proto\x12\x14onlyalpha.gateway.v1\x1a*onlyalpha_gateway_protocol/v1/common.proto\x1a)onlyalpha_gateway_protocol/v1/error.proto\x1a,onlyalpha_gateway_protocol/v1/identity.proto\"\x83\x01\n\x10HandshakeRequest\x12\x16\n\x0eprotocol_major\x18\x01 \x01(\r\x12?\n\x15required_capabilities\x18\x02 \x03(\x0e\x32 .onlyalpha.gateway.v1.Capability\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\"\x88\x02\n\x11HandshakeResponse\x12\x37\n\x08identity\x18\x01 \x01(\x0b\x32%.onlyalpha.gateway.v1.GatewayIdentity\x12\x16\n\x0eprotocol_major\x18\x02 \x01(\r\x12\x17\n\x0f\x63ontract_sha256\x18\x03 \x01(\t\x12\x1e\n\x16implementation_version\x18\x04 \x01(\t\x12\x36\n\x0c\x63\x61pabilities\x18\x05 \x03(\x0e\x32 .onlyalpha.gateway.v1.Capability\x12\x31\n\x05\x65rror\x18\x06 \x01(\x0b\x32\".onlyalpha.gateway.v1.GatewayError\"j\n\x18\x41pplyTestMutationRequest\x12=\n\x08identity\x18\x01 \x01(\x0b\x32+.onlyalpha.gateway.v1.RemoteCommandIdentity\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\xa1\x01\n\x19\x41pplyTestMutationResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x12\n\noutcome_id\x18\x02 \x01(\t\x12\x17\n\x0f\x65xecution_count\x18\x03 \x01(\x04\x12\x10\n\x08replayed\x18\x04 \x01(\x08\x12\x31\n\x05\x65rror\x18\x05 \x01(\x0b\x32\".onlyalpha.gateway.v1.GatewayError2\xe4\x01\n\x0eGatewayService\x12\\\n\tHandshake\x12&.onlyalpha.gateway.v1.HandshakeRequest\x1a\'.onlyalpha.gateway.v1.HandshakeResponse\x12t\n\x11\x41pplyTestMutation\x12..onlyalpha.gateway.v1.ApplyTestMutationRequest\x1a/.onlyalpha.gateway.v1.ApplyTestMutationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onlyalpha_gateway_protocol.v1.gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDSHAKEREQUEST']._serialized_start=203
  _globals['_HANDSHAKEREQUEST']._serialized_end=334
  _globals['_HANDSHAKERESPONSE']._serialized_start=337
  _globals['_HANDSHAKERESPONSE']._serialized_end=601
  _globals['_APPLYTESTMUTATIONREQUEST']._serialized_start=603
  _globals['_APPLYTESTMUTATIONREQUEST']._serialized_end=709
  _globals['_APPLYTESTMUTATIONRESPONSE']._serialized_start=712
  _globals['_APPLYTESTMUTATIONRESPONSE']._serialized_end=873
  _globals['_GATEWAYSERVICE']._serialized_start=876
  _globals['_GATEWAYSERVICE']._serialized_end=1104
# @@protoc_insertion_point(module_scope)
