# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: onlyalpha_gateway_protocol/v1/stream.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'onlyalpha_gateway_protocol/v1/stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from onlyalpha_gateway_protocol.v1 import error_pb2 as onlyalpha__gateway__protocol_dot_v1_dot_error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*onlyalpha_gateway_protocol/v1/stream.proto\x12\x14onlyalpha.gateway.v1\x1a)onlyalpha_gateway_protocol/v1/error.proto\"^\n\x16WatchTestEventsRequest\x12\x1b\n\x13gateway_instance_id\x18\x01 \x01(\t\x12\x11\n\tstream_id\x18\x02 \x01(\t\x12\x14\n\x0cresume_after\x18\x03 \x01(\x04\"\x90\x01\n\tTestEvent\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x1b\n\x13gateway_instance_id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x04\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\t\x12\x1e\n\x16observed_at_unix_nanos\x18\x05 \x01(\x03\x12\x0f\n\x07payload\x18\x06 \x01(\t\"\x7f\n\x0eTestStreamItem\x12\x30\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x1f.onlyalpha.gateway.v1.TestEventH\x00\x12\x33\n\x05\x65rror\x18\x02 \x01(\x0b\x32\".onlyalpha.gateway.v1.GatewayErrorH\x00\x42\x06\n\x04item2\x7f\n\x14GatewayStreamService\x12g\n\x0fWatchTestEvents\x12,.onlyalpha.gateway.v1.WatchTestEventsRequest\x1a$.onlyalpha.gateway.v1.TestStreamItem0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onlyalpha_gateway_protocol.v1.stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WATCHTESTEVENTSREQUEST']._serialized_start=111
  _globals['_WATCHTESTEVENTSREQUEST']._serialized_end=205
  _globals['_TESTEVENT']._serialized_start=208
  _globals['_TESTEVENT']._serialized_end=352
  _globals['_TESTSTREAMITEM']._serialized_start=354
  _globals['_TESTSTREAMITEM']._serialized_end=481
  _globals['_GATEWAYSTREAMSERVICE']._serialized_start=483
  _globals['_GATEWAYSTREAMSERVICE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
