"""Stable Risk component enumerations."""

from enum import StrEnum


class OnlyRiskRuleScope(StrEnum):
    SYSTEM = "SYSTEM"
    RUNTIME = "RUNTIME"
    ACCOUNT = "ACCOUNT"
    INSTRUMENT = "INSTRUMENT"
    CLUSTER = "CLUSTER"


class OnlyRiskRuleMode(StrEnum):
    ENFORCING = "ENFORCING"
    OBSERVING = "OBSERVING"


class OnlyRiskOutcome(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    ERROR = "ERROR"


class OnlyRiskSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class OnlyRiskRejectionCode(StrEnum):
    INSTRUMENT_NOT_FOUND = "INSTRUMENT_NOT_FOUND"
    INSTRUMENT_NOT_TRADABLE = "INSTRUMENT_NOT_TRADABLE"
    UNSUPPORTED_ORDER_TYPE = "UNSUPPORTED_ORDER_TYPE"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_PRICE_INCREMENT = "INVALID_PRICE_INCREMENT"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INVALID_QUANTITY_INCREMENT = "INVALID_QUANTITY_INCREMENT"
    MINIMUM_QUANTITY_NOT_MET = "MINIMUM_QUANTITY_NOT_MET"
    MAXIMUM_QUANTITY_EXCEEDED = "MAXIMUM_QUANTITY_EXCEEDED"
    MINIMUM_NOTIONAL_NOT_MET = "MINIMUM_NOTIONAL_NOT_MET"
    MAXIMUM_ORDER_NOTIONAL_EXCEEDED = "MAXIMUM_ORDER_NOTIONAL_EXCEEDED"
    OUTSIDE_TRADING_SESSION = "OUTSIDE_TRADING_SESSION"
    PRICE_LIMIT_EXCEEDED = "PRICE_LIMIT_EXCEEDED"
    CLUSTER_NOT_AUTHORIZED = "CLUSTER_NOT_AUTHORIZED"
    ACCOUNT_NOT_AUTHORIZED = "ACCOUNT_NOT_AUTHORIZED"
    DUPLICATE_ORDER_REQUEST = "DUPLICATE_ORDER_REQUEST"
    MAX_ACTIVE_ORDERS_EXCEEDED = "MAX_ACTIVE_ORDERS_EXCEEDED"
    MAX_CLUSTER_ACTIVE_ORDERS_EXCEEDED = "MAX_CLUSTER_ACTIVE_ORDERS_EXCEEDED"
    MAX_INSTRUMENT_ACTIVE_ORDERS_EXCEEDED = "MAX_INSTRUMENT_ACTIVE_ORDERS_EXCEEDED"
    RISK_RESERVATION_EXCEEDED = "RISK_RESERVATION_EXCEEDED"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    REQUIRED_RISK_DATA_MISSING = "REQUIRED_RISK_DATA_MISSING"
    RISK_RULE_ERROR = "RISK_RULE_ERROR"


class OnlyRiskLevel(StrEnum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"


class OnlyRiskReservationType(StrEnum):
    ORDER = "ORDER"


class OnlyRiskReservationState(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    CONSUMED = "CONSUMED"
    FAILED = "FAILED"


class OnlyRiskReleaseReason(StrEnum):
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_EXPIRED = "ORDER_EXPIRED"
    ORDER_FAILED = "ORDER_FAILED"
    CLUSTER_STOPPED = "CLUSTER_STOPPED"
    EXECUTION_REJECTED = "EXECUTION_REJECTED"


class OnlyRiskReservationApplyResult(StrEnum):
    APPLIED = "APPLIED"
    DUPLICATE = "DUPLICATE"
    INVALID = "INVALID"
    NOT_FOUND = "NOT_FOUND"


class OnlyKillSwitchState(StrEnum):
    INACTIVE = "INACTIVE"
    ACTIVE = "ACTIVE"


class OnlyRiskAdjustmentPolicy(StrEnum):
    REJECT = "REJECT"
