"""Broker capabilities, connection lifecycle and operation results."""

from enum import StrEnum


class OnlyBrokerCapability(StrEnum):
    CONNECT = "CONNECT"
    AUTHENTICATE = "AUTHENTICATE"
    SUBMIT_ORDER = "SUBMIT_ORDER"
    CANCEL_ORDER = "CANCEL_ORDER"
    QUERY_ACCOUNT = "QUERY_ACCOUNT"
    QUERY_BALANCES = "QUERY_BALANCES"
    QUERY_POSITIONS = "QUERY_POSITIONS"
    QUERY_OPEN_ORDERS = "QUERY_OPEN_ORDERS"
    QUERY_ORDERS = "QUERY_ORDERS"
    QUERY_TRADES = "QUERY_TRADES"
    PUSH_ORDER_UPDATES = "PUSH_ORDER_UPDATES"
    PUSH_TRADE_UPDATES = "PUSH_TRADE_UPDATES"
    PUSH_ACCOUNT_UPDATES = "PUSH_ACCOUNT_UPDATES"
    PUSH_POSITION_UPDATES = "PUSH_POSITION_UPDATES"
    MARKET_ORDER = "MARKET_ORDER"
    LIMIT_ORDER = "LIMIT_ORDER"
    PARTIAL_FILL = "PARTIAL_FILL"


class OnlyBrokerConnectionState(StrEnum):
    DISCONNECTED = "DISCONNECTED"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    AUTHENTICATING = "AUTHENTICATING"
    READY = "READY"
    RECONNECTING = "RECONNECTING"
    FAILED = "FAILED"


class OnlyBrokerOperationStatus(StrEnum):
    RECEIVED = "RECEIVED"
    REJECTED = "REJECTED"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    NOT_READY = "NOT_READY"
