"""Project the server's Market Data bars DTO to the browser validator."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from market_data_stream_contract import _definitions, _expression
from onlyalpha_http_server.market_data.schema import MarketDataBarsDto

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "packages/onlyalpha-web-console/src/api/marketData/http.generated.ts"


def render() -> str:
    document = MarketDataBarsDto.model_json_schema()
    lines = [
        "// Generated by scripts/market_data_http_contract.py; do not edit.",
        'import { z } from "zod";',
        "",
    ]
    for name, schema in _definitions(document):
        lines.append(f"const {name}Schema = {_expression(schema)};")
    lines += [
        f"export const marketDataBarsSchema = {_expression(document)}.refine(value => {{",
        '    const complete = value.coverage.status === "COMPLETE";',
        "    return (value.resume_after_sequence !== null) === complete &&",
        "        (value.resume_plan_fingerprint !== null) === complete;",
        "});",
        "export type MarketDataBars = z.infer<typeof marketDataBarsSchema>;",
        "",
    ]
    return subprocess.run(
        [str(ROOT / "packages/onlyalpha-web-console/node_modules/.bin/prettier"), "--stdin-filepath", str(WEB)],
        input="\n".join(lines),
        text=True,
        capture_output=True,
        check=True,
    ).stdout


def main() -> None:
    rendered = render()
    if sys.argv[1:] == ["write"]:
        WEB.write_text(rendered, encoding="utf-8")
    elif sys.argv[1:] == ["check"]:
        if WEB.read_text(encoding="utf-8") != rendered:
            raise SystemExit(
                "Market Data HTTP contract projection is stale; run scripts/market_data_http_contract.py write"
            )
    else:
        raise SystemExit("usage: market_data_http_contract.py write|check")


if __name__ == "__main__":
    main()
