"""Project the server's one WebSocket contract to JSON Schema and Web Zod."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

from onlyalpha_http_server.market_data.stream_schema import (
    MarketDataStreamSubscribeDto,
    market_data_stream_event_adapter,
)

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "contracts/product-api/v2/market-data-stream.schema.json"
WEB = ROOT / "packages/onlyalpha-web-console/src/api/marketData/stream.generated.ts"


def _expression(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).split("/")[-1] + "Schema"
    if "anyOf" in schema:
        variants = schema["anyOf"]
        if len(variants) == 2 and {part.get("type") for part in variants} == {"string", "null"}:
            return _expression(next(part for part in variants if part.get("type") == "string")) + ".nullable()"
        return "z.union([" + ", ".join(_expression(part) for part in variants) + "])"
    if "oneOf" in schema:
        return "z.union([" + ", ".join(_expression(part) for part in schema["oneOf"]) + "])"
    if "const" in schema:
        return f"z.literal({json.dumps(schema['const'])})"
    if "enum" in schema:
        return "z.enum([" + ", ".join(json.dumps(item) for item in schema["enum"]) + "])"
    kind = schema.get("type")
    if kind == "string":
        result = "z.string()"
        if "minLength" in schema:
            result += f".min({schema['minLength']})"
        if "pattern" in schema:
            result += f".regex(new RegExp({json.dumps(schema['pattern'])}))"
        return result
    if kind == "integer":
        result = "z.number().int()"
        if "minimum" in schema:
            result += f".min({schema['minimum']})"
        if "maximum" in schema:
            result += f".max({schema['maximum']})"
        return result
    if kind == "boolean":
        return "z.boolean()"
    if kind == "array":
        return f"z.array({_expression(schema['items'])})"
    if kind == "null":
        return "z.null()"
    if kind == "object":
        required = set(schema.get("required", []))
        fields = [
            f"    {json.dumps(name)}: {_expression(value)}{'' if name in required else '.optional()'}"
            for name, value in schema["properties"].items()
        ]
        return "z.strictObject({\n" + ",\n".join(fields) + "\n})"
    raise ValueError(f"unsupported stream contract schema: {schema}")


def _definitions(document: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    definitions = document["$defs"]
    result: list[tuple[str, dict[str, Any]]] = []
    pending = dict(definitions)
    while pending:
        ready = [
            name for name, schema in pending.items() if all(ref.split("/")[-1] not in pending for ref in _refs(schema))
        ]
        if not ready:
            raise ValueError("recursive stream contract is unsupported")
        for name in ready:
            result.append((name, pending.pop(name)))
    return result


def _refs(value: Any) -> list[str]:
    if isinstance(value, dict):
        return ([value["$ref"]] if "$ref" in value else []) + [ref for child in value.values() for ref in _refs(child)]
    if isinstance(value, list):
        return [ref for child in value for ref in _refs(child)]
    return []


def render() -> tuple[str, str]:
    subscribe = MarketDataStreamSubscribeDto.model_json_schema()
    event = market_data_stream_event_adapter.json_schema()
    definitions = {**subscribe.pop("$defs"), **event.pop("$defs")}
    document: dict[str, Any] = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "onlyalpha.product-api.v2.market-data-stream",
        "$defs": definitions,
        "oneOf": [{"$ref": "#/$defs/subscribe"}, {"$ref": "#/$defs/event"}],
    }
    document["$defs"]["subscribe"] = subscribe
    document["$defs"]["subscribe"]["if"] = {"properties": {"resume_after_sequence": {"not": {"const": "0"}}}}
    document["$defs"]["subscribe"]["then"] = {
        "required": ["resume_plan_fingerprint"],
        "properties": {"resume_plan_fingerprint": {"type": "string"}},
    }
    document["$defs"]["event"] = event
    lines = ["// Generated by scripts/market_data_stream_contract.py; do not edit.", 'import { z } from "zod";', ""]
    for name, schema in _definitions(document):
        if name in {"subscribe", "event"}:
            continue
        lines.append(f"const {name}Schema = {_expression(schema)};")
    lines += [
        f'export const marketDataStreamSubscribeSchema = {_expression(subscribe)}.refine(value => value.resume_after_sequence === "0" || value.resume_plan_fingerprint !== null && value.resume_plan_fingerprint !== undefined);',
        f"export const marketDataStreamEventSchema = {_expression(event)};",
        "export type MarketDataStreamSubscribe = z.infer<typeof marketDataStreamSubscribeSchema>;",
        "export type MarketDataStreamEvent = z.infer<typeof marketDataStreamEventSchema>;",
        "",
    ]
    web = subprocess.run(
        [str(ROOT / "packages/onlyalpha-web-console/node_modules/.bin/prettier"), "--stdin-filepath", str(WEB)],
        input="\n".join(lines),
        text=True,
        capture_output=True,
        check=True,
    ).stdout
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n", web


def main() -> None:
    schema, web = render()
    if sys.argv[1:] == ["write"]:
        SCHEMA.write_text(schema, encoding="utf-8")
        WEB.write_text(web, encoding="utf-8")
    elif sys.argv[1:] == ["check"]:
        if SCHEMA.read_text(encoding="utf-8") != schema or WEB.read_text(encoding="utf-8") != web:
            raise SystemExit(
                "Market Data Stream contract projection is stale; run scripts/market_data_stream_contract.py write"
            )
    else:
        raise SystemExit("usage: market_data_stream_contract.py write|check")


if __name__ == "__main__":
    main()
