/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/research/artifacts/{research_result_fingerprint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact Summary */
        get: operations["artifact_summary_api_v2_research_artifacts__research_result_fingerprint__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Catalog */
        get: operations["candidate_catalog_api_v2_research_artifacts__research_result_fingerprint__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/candidates/{candidate_fingerprint}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Graph */
        get: operations["candidate_graph_api_v2_research_artifacts__research_result_fingerprint__candidates__candidate_fingerprint__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/market/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Series */
        get: operations["market_series_api_v2_research_artifacts__research_result_fingerprint__market_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/signals/{candidate_fingerprint}/{role}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Series */
        get: operations["signal_series_api_v2_research_artifacts__research_result_fingerprint__signals__candidate_fingerprint___role__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistics Catalog */
        get: operations["statistics_catalog_api_v2_research_artifacts__research_result_fingerprint__statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/statistics/{statistics_fingerprint}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistic Series */
        get: operations["statistic_series_api_v2_research_artifacts__research_result_fingerprint__statistics__statistics_fingerprint__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Variable Catalog */
        get: operations["variable_catalog_api_v2_research_artifacts__research_result_fingerprint__variables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/artifacts/{research_result_fingerprint}/variables/{calculation_fingerprint}/{node_fingerprint}/{output_name}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Variable Series */
        get: operations["variable_series_api_v2_research_artifacts__research_result_fingerprint__variables__calculation_fingerprint___node_fingerprint___output_name__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/catalog/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculations */
        get: operations["calculations_api_v2_research_catalog_calculations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/catalog/dataset-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Fields */
        get: operations["dataset_fields_api_v2_research_catalog_dataset_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/catalog/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistics */
        get: operations["statistics_api_v2_research_catalog_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/catalog/universes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universes */
        get: operations["universes_api_v2_research_catalog_universes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/definitions/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Definition */
        post: operations["resolve_definition_api_v2_research_definitions_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v2_research_runs_get"];
        put?: never;
        /** Submit Run */
        post: operations["submit_run_api_v2_research_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v2_research_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/research/runs/{run_id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v2_research_runs__run_id__cancellation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /**
         * OnlyAdjustmentType
         * @enum {string}
         */
        OnlyAdjustmentType: "RAW" | "FORWARD" | "BACKWARD";
        /**
         * OnlyAggregationSource
         * @enum {string}
         */
        OnlyAggregationSource: "EXTERNAL" | "INTERNAL";
        /**
         * OnlyBarAggregation
         * @enum {string}
         */
        OnlyBarAggregation: "TIME" | "TICK" | "VOLUME" | "VALUE";
        /**
         * OnlyCalculationDataType
         * @enum {string}
         */
        OnlyCalculationDataType: "DECIMAL" | "INTEGER" | "BOOLEAN" | "STRING";
        /**
         * OnlyPriceType
         * @enum {string}
         */
        OnlyPriceType: "LAST" | "BID" | "ASK" | "MID" | "MARK";
        /**
         * OnlyResearchPairingPolicy
         * @enum {string}
         */
        OnlyResearchPairingPolicy: "PAIRWISE_COMPLETE";
        /**
         * OnlyResearchRankTieMethod
         * @enum {string}
         */
        OnlyResearchRankTieMethod: "AVERAGE";
        /**
         * OnlyResearchStatisticsMethod
         * @enum {string}
         */
        OnlyResearchStatisticsMethod: "IC" | "RANK_IC";
        /**
         * OnlyResearchUniverseKind
         * @enum {string}
         */
        OnlyResearchUniverseKind: "SINGLE_INSTRUMENT" | "EXPLICIT_INSTRUMENT_SET" | "REGISTERED_POOL" | "REGISTERED_UNIVERSE";
        /**
         * OnlyResearchUniversePolicy
         * @enum {string}
         */
        OnlyResearchUniversePolicy: "OBSERVED_PAIRWISE";
        /**
         * OnlyResearchWeighting
         * @enum {string}
         */
        OnlyResearchWeighting: "EQUAL";
        /** ResearchAndDto */
        ResearchAndDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "AND";
            /** Operands */
            operands: (components["schemas"]["ResearchComparisonDto"] | components["schemas"]["ResearchNotDto"] | components["schemas"]["ResearchAndDto"] | components["schemas"]["ResearchOrDto"])[];
        };
        /** ResearchArtifactSummaryDto */
        ResearchArtifactSummaryDto: {
            /** Artifact Content Fingerprint */
            artifact_content_fingerprint: string;
            /** Artifact Profile */
            artifact_profile: string;
            /** Artifact Schema Version */
            artifact_schema_version: number;
            /** Candidate Count */
            candidate_count: number;
            /** Created At */
            created_at: string;
            /** Dataset Snapshot Fingerprint */
            dataset_snapshot_fingerprint: string;
            /** Instrument Ids */
            instrument_ids: string[];
            /** Market Row Count */
            market_row_count: number;
            /** Published Series Count */
            published_series_count: number;
            /** Research Result Content Fingerprint */
            research_result_content_fingerprint: string;
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /** Research Result Plan Fingerprint */
            research_result_plan_fingerprint: string;
            /** Research Result Schema Version */
            research_result_schema_version: number;
            /** Row Count */
            row_count: number;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Signal Series Count */
            signal_series_count: number;
            /** Statistics Count */
            statistics_count: number;
        };
        /** ResearchBarSpecificationDto */
        ResearchBarSpecificationDto: {
            aggregation: components["schemas"]["OnlyBarAggregation"];
            price_type: components["schemas"]["OnlyPriceType"];
            /** Step */
            step: number;
        };
        /** ResearchCalculationCatalogDto */
        ResearchCalculationCatalogDto: {
            /** Calculations */
            calculations: components["schemas"]["ResearchCalculationCatalogItemDto"][];
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchCalculationCatalogItemDto */
        ResearchCalculationCatalogItemDto: {
            /** Inputs */
            inputs: components["schemas"]["ResearchInputDefinitionDto"][];
            /** Kind */
            kind: string;
            /** Outputs */
            outputs: components["schemas"]["ResearchOutputDefinitionDto"][];
            /** Parameter Sweep Allowed */
            parameter_sweep_allowed: boolean;
            /** Parameters */
            parameters: components["schemas"]["ResearchParameterDefinitionDto"][];
            type_reference: components["schemas"]["ResearchCalculationTypeReferenceDto"];
        };
        /** ResearchCalculationGraphDto */
        ResearchCalculationGraphDto: {
            /** Nodes */
            nodes: components["schemas"]["ResearchGraphNodeDto"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
        };
        /** ResearchCalculationInputDto */
        ResearchCalculationInputDto: {
            /** Input Name */
            input_name: string;
            /** Source */
            source: string | components["schemas"]["ResearchVariableRefDto"];
        };
        /** ResearchCalculationInstanceDto */
        ResearchCalculationInstanceDto: {
            /** Input Bindings */
            input_bindings: components["schemas"]["ResearchCalculationInputDto"][];
            /** Instance Key */
            instance_key: string;
            /** Parameters */
            parameters: {
                [key: string]: components["schemas"]["ResearchFixedParameterDto"] | components["schemas"]["ResearchSweepParameterDto"];
            };
            /** Primary Output */
            primary_output: string | null;
            /** Published Outputs */
            published_outputs: string[];
            type_reference: components["schemas"]["ResearchCalculationTypeReferenceDto"];
        };
        /** ResearchCalculationTypeReferenceDto */
        ResearchCalculationTypeReferenceDto: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "INDICATOR" | "FACTOR" | "TARGET";
            /** Semantic Version */
            semantic_version: string;
            /** Type Id */
            type_id: string;
        };
        /** ResearchCandidateCatalogDto */
        ResearchCandidateCatalogDto: {
            /** Candidates */
            candidates: components["schemas"]["ResearchCandidateDto"][];
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchCandidateDto */
        ResearchCandidateDto: {
            /** Assignment */
            assignment: {
                [key: string]: boolean | number | string | null;
            };
            /** Assignment Types */
            assignment_types: {
                [key: string]: "NULL" | "BOOLEAN" | "INTEGER" | "DECIMAL" | "STRING";
            };
            /** Calculation Fingerprint */
            calculation_fingerprint: string;
            /** Candidate Calculation Id */
            candidate_calculation_id: string;
            /** Candidate Fingerprint */
            candidate_fingerprint: string;
            /** Graph Fingerprint */
            graph_fingerprint: string;
            /** Signal Roles */
            signal_roles: ("ELIGIBILITY" | "ENTRY_SIGNAL" | "EXIT_SIGNAL")[];
            /** Statistics Fingerprints */
            statistics_fingerprints: string[];
        };
        /** ResearchCandidateGraphDto */
        ResearchCandidateGraphDto: {
            /** Calculation Fingerprint */
            calculation_fingerprint: string;
            /** Candidate Fingerprint */
            candidate_fingerprint: string;
            graph: components["schemas"]["ResearchCalculationGraphDto"];
            /** Graph Fingerprint */
            graph_fingerprint: string;
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchComparisonDto */
        ResearchComparisonDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "COMPARISON";
            /** Left */
            left: components["schemas"]["ResearchDatasetFieldRefDto"] | components["schemas"]["ResearchVariableRefDto"] | components["schemas"]["ResearchTypedLiteralDto"];
            /**
             * Operator
             * @enum {string}
             */
            operator: "==" | "!=" | "<" | "<=" | ">" | ">=";
            /** Right */
            right: components["schemas"]["ResearchDatasetFieldRefDto"] | components["schemas"]["ResearchVariableRefDto"] | components["schemas"]["ResearchTypedLiteralDto"];
        };
        /** ResearchDatasetFieldCatalogDto */
        ResearchDatasetFieldCatalogDto: {
            /** Dataset Fields */
            dataset_fields: components["schemas"]["ResearchDatasetFieldDto"][];
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchDatasetFieldDto */
        ResearchDatasetFieldDto: {
            /** Data Type */
            data_type: string;
            /** Dimensions */
            dimensions: string[];
            /** Field Name */
            field_name: string;
            /** Semantic Roles */
            semantic_roles: string[];
            /** Source */
            source: string;
            /** Unit */
            unit: string | null;
        };
        /** ResearchDatasetFieldRefDto */
        ResearchDatasetFieldRefDto: {
            /** Field Name */
            field_name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "DATASET_FIELD";
        };
        /** ResearchDatasetSelectionDto */
        ResearchDatasetSelectionDto: {
            /** Adjustment Reference */
            adjustment_reference: string | null;
            adjustment_type: components["schemas"]["OnlyAdjustmentType"];
            aggregation_source: components["schemas"]["OnlyAggregationSource"];
            bar_specification: components["schemas"]["ResearchBarSpecificationDto"];
            /** End */
            end: string;
            /** Start */
            start: string;
            universe: components["schemas"]["ResearchUniverseSelectionDto"];
        };
        /** ResearchDefinitionCandidateDto */
        ResearchDefinitionCandidateDto: {
            /** Assignment */
            assignment: {
                [key: string]: components["schemas"]["ResearchScalarDto"];
            };
            /** Calculation Fingerprint */
            calculation_fingerprint: string;
            /** Candidate Fingerprint */
            candidate_fingerprint: string;
            /** Graph Fingerprint */
            graph_fingerprint: string;
            /** Ordinal */
            ordinal: number;
        };
        /** ResearchDefinitionErrorDto */
        ResearchDefinitionErrorDto: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Path */
            path: string;
            /** Phase */
            phase: string;
        };
        /** ResearchDefinitionErrorEnvelopeDto */
        ResearchDefinitionErrorEnvelopeDto: {
            error: components["schemas"]["ResearchDefinitionErrorDto"];
        };
        /** ResearchDefinitionRequestDto */
        ResearchDefinitionRequestDto: {
            /** Calculations */
            calculations: components["schemas"]["ResearchCalculationInstanceDto"][];
            dataset: components["schemas"]["ResearchDatasetSelectionDto"];
            /** Display Metadata */
            display_metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Eligibility */
            eligibility: (components["schemas"]["ResearchComparisonDto"] | components["schemas"]["ResearchNotDto"] | components["schemas"]["ResearchAndDto"] | components["schemas"]["ResearchOrDto"]) | null;
            /** Schema Version */
            schema_version: number;
            signals: components["schemas"]["ResearchSignalsDto"];
            /** Statistics */
            statistics: components["schemas"]["ResearchStatisticsRequestDto"][];
            /** Targets */
            targets: components["schemas"]["ResearchCalculationInstanceDto"][];
        };
        /** ResearchDefinitionResolutionDto */
        ResearchDefinitionResolutionDto: {
            /** Authoring Definition Fingerprint */
            authoring_definition_fingerprint: string;
            /** Candidate Count */
            candidate_count: number;
            /** Candidates */
            candidates: components["schemas"]["ResearchDefinitionCandidateDto"][];
            /** Dataset Snapshot Fingerprint */
            dataset_snapshot_fingerprint: string;
            /** Diagnostics */
            diagnostics: components["schemas"]["JsonValue"][];
            /** Exact Specification */
            exact_specification: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Instrument Count */
            instrument_count: number;
            /** Published Variables */
            published_variables: components["schemas"]["ResearchPublishedVariableDto"][];
            /** Resolved Dataset Definition */
            resolved_dataset_definition: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Resolved Definition Fingerprint */
            resolved_definition_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Specification Fingerprint */
            specification_fingerprint: string;
        };
        /** ResearchErrorDto */
        ResearchErrorDto: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchFixedParameterDto */
        ResearchFixedParameterDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "FIXED";
            value: components["schemas"]["ResearchScalarDto"];
        };
        /** ResearchGraphBooleanScalarDto */
        ResearchGraphBooleanScalarDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "BOOLEAN";
            /** Value */
            value: boolean;
        };
        /** ResearchGraphDecimalScalarDto */
        ResearchGraphDecimalScalarDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DECIMAL";
            /** Value */
            value: string;
        };
        /** ResearchGraphDefinitionDto */
        ResearchGraphDefinitionDto: {
            /** Extensions */
            extensions: {
                [key: string]: components["schemas"]["ResearchGraphNullScalarDto"] | components["schemas"]["ResearchGraphBooleanScalarDto"] | components["schemas"]["ResearchGraphIntegerScalarDto"] | components["schemas"]["ResearchGraphDecimalScalarDto"] | components["schemas"]["ResearchGraphStringScalarDto"];
            };
            /** Factor Kind */
            factor_kind: ("TIME_SERIES" | "CROSS_SECTION") | null;
            /** Input Bindings */
            input_bindings: {
                [key: string]: components["schemas"]["ResearchGraphReferenceDto"];
            };
            /** Inputs */
            inputs: components["schemas"]["ResearchGraphPortDto"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "INDICATOR" | "FACTOR" | "TARGET" | "PREDICATE";
            /**
             * Missing Values
             * @enum {string}
             */
            missing_values: "FAIL" | "SKIP" | "PROPAGATE" | "RESET";
            numeric: components["schemas"]["ResearchGraphNumericDto"];
            /** Outputs */
            outputs: components["schemas"]["ResearchGraphPortDto"][];
            /** Parameters */
            parameters: {
                [key: string]: components["schemas"]["ResearchGraphNullScalarDto"] | components["schemas"]["ResearchGraphBooleanScalarDto"] | components["schemas"]["ResearchGraphIntegerScalarDto"] | components["schemas"]["ResearchGraphDecimalScalarDto"] | components["schemas"]["ResearchGraphStringScalarDto"];
            };
            /**
             * Schema Version
             * @constant
             */
            schema_version: 2;
            /** Semantic Version */
            semantic_version: string;
            /**
             * Timestamp
             * @enum {string}
             */
            timestamp: "BAR_OPEN" | "BAR_CLOSE" | "EVENT_TIME" | "OBSERVATION_TIME" | "AVAILABILITY_TIME";
            /** Type Id */
            type_id: string;
            warmup: components["schemas"]["ResearchGraphWarmupDto"];
        };
        /** ResearchGraphIntegerScalarDto */
        ResearchGraphIntegerScalarDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "INTEGER";
            /** Value */
            value: string;
        };
        /** ResearchGraphNodeDto */
        ResearchGraphNodeDto: {
            /** Alias */
            alias: string | null;
            definition: components["schemas"]["ResearchGraphDefinitionDto"];
            /** Node Fingerprint */
            node_fingerprint: string;
        };
        /** ResearchGraphNullScalarDto */
        ResearchGraphNullScalarDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NULL";
            /** Value */
            value: null;
        };
        /** ResearchGraphNumericDto */
        ResearchGraphNumericDto: {
            /** Output Quantum */
            output_quantum: string | null;
            /** Precision */
            precision: number;
            /** Representation */
            representation: string;
            /** Rounding */
            rounding: string;
        };
        /** ResearchGraphPortDto */
        ResearchGraphPortDto: {
            /**
             * Data Type
             * @enum {string}
             */
            data_type: "DECIMAL" | "INTEGER" | "BOOLEAN" | "STRING";
            /** Dimensions */
            dimensions: string[];
            /** Name */
            name: string;
            /** Nullable */
            nullable: boolean;
            /** Semantic Type */
            semantic_type: string;
            /** Unit */
            unit: string | null;
        };
        /** ResearchGraphReferenceDto */
        ResearchGraphReferenceDto: {
            /** Node Fingerprint */
            node_fingerprint: string | null;
            /** Output Name */
            output_name: string;
            /** Source */
            source: string | null;
        };
        /** ResearchGraphStringScalarDto */
        ResearchGraphStringScalarDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "STRING";
            /** Value */
            value: string;
        };
        /** ResearchGraphWarmupDto */
        ResearchGraphWarmupDto: {
            /** Initialization */
            initialization: string;
            /** Minimum Observations */
            minimum_observations: number;
            /**
             * Pre Ready Output
             * @enum {string}
             */
            pre_ready_output: "NULL" | "PARTIAL";
            /** Ready Condition */
            ready_condition: string;
        };
        /** ResearchHealthDto */
        ResearchHealthDto: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Reason */
            reason?: string | null;
            /** Status */
            status: string;
        };
        /** ResearchInputDefinitionDto */
        ResearchInputDefinitionDto: {
            /** Data Type */
            data_type: string;
            /** Dimensions */
            dimensions: string[];
            /** Name */
            name: string;
            /** Nullable */
            nullable: boolean;
            /** Semantic Type */
            semantic_type: string;
            /** Unit */
            unit: string | null;
        };
        /** ResearchMarketPointDto */
        ResearchMarketPointDto: {
            /** Close */
            close: string;
            /** High */
            high: string;
            /** Instrument Id */
            instrument_id: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /** Ts Event Ns */
            ts_event_ns: string;
            /** Volume */
            volume: string;
        };
        /** ResearchNotDto */
        ResearchNotDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "NOT";
            /** Operand */
            operand: components["schemas"]["ResearchComparisonDto"] | components["schemas"]["ResearchNotDto"] | components["schemas"]["ResearchAndDto"] | components["schemas"]["ResearchOrDto"];
        };
        /** ResearchNumericDefinitionDto */
        ResearchNumericDefinitionDto: {
            /** Output Quantum */
            output_quantum: string;
            /** Precision */
            precision: number;
            /** Representation */
            representation: string;
            /** Rounding */
            rounding: string;
        };
        /** ResearchOrDto */
        ResearchOrDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "OR";
            /** Operands */
            operands: (components["schemas"]["ResearchComparisonDto"] | components["schemas"]["ResearchNotDto"] | components["schemas"]["ResearchAndDto"] | components["schemas"]["ResearchOrDto"])[];
        };
        /** ResearchOutputDefinitionDto */
        ResearchOutputDefinitionDto: {
            /** Data Type */
            data_type: string;
            /** Dimensions */
            dimensions: string[];
            /** Name */
            name: string;
            /** Nullable */
            nullable: boolean;
            /** Semantic Type */
            semantic_type: string;
            /** Unit */
            unit: string | null;
        };
        /** ResearchParameterDefinitionDto */
        ResearchParameterDefinitionDto: {
            default: components["schemas"]["ResearchScalarDto"];
            /** Enum Values */
            enum_values: components["schemas"]["ResearchScalarDto"][];
            maximum: components["schemas"]["ResearchScalarDto"] | null;
            minimum: components["schemas"]["ResearchScalarDto"] | null;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /** Type */
            type: string;
            /** Uppercase */
            uppercase: boolean;
        };
        /** ResearchPublishedSeriesCatalogDto */
        ResearchPublishedSeriesCatalogDto: {
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Series */
            series: components["schemas"]["ResearchPublishedSeriesDto"][];
        };
        /** ResearchPublishedSeriesDto */
        ResearchPublishedSeriesDto: {
            /** Calculation Fingerprint */
            calculation_fingerprint: string;
            /** Candidate Fingerprint */
            candidate_fingerprint: string | null;
            /** Node Fingerprint */
            node_fingerprint: string;
            /** Output Name */
            output_name: string;
            /** Value Kind */
            value_kind: string;
        };
        /** ResearchPublishedVariableDto */
        ResearchPublishedVariableDto: {
            /** Data Type */
            data_type: string;
            /** Instance Key */
            instance_key: string;
            /** Output Name */
            output_name: string;
            /** Semantic Type */
            semantic_type: string;
        };
        /** ResearchRegisteredUniverseDto */
        ResearchRegisteredUniverseDto: {
            /** Display Metadata */
            display_metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Kind */
            kind: string;
            /** Registered Id */
            registered_id: string;
        };
        /** ResearchRunDto */
        ResearchRunDto: {
            /** Admission Resolution Fingerprint */
            admission_resolution_fingerprint: string;
            /** Artifact Ref */
            artifact_ref: string | null;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            failure: components["schemas"]["ResearchRunFailureDto"] | null;
            /** Finished At */
            finished_at: string | null;
            /** Queued At */
            queued_at: string;
            /** Result Ref */
            result_ref: string | null;
            /** Revision */
            revision: string;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Specification */
            specification: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Specification Fingerprint */
            specification_fingerprint: string;
            /** Specification Schema Version */
            specification_schema_version: number;
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
        };
        /** ResearchRunErrorDto */
        ResearchRunErrorDto: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Phase */
            phase: string;
        };
        /** ResearchRunErrorEnvelopeDto */
        ResearchRunErrorEnvelopeDto: {
            error: components["schemas"]["ResearchRunErrorDto"];
        };
        /** ResearchRunFailureDto */
        ResearchRunFailureDto: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Phase */
            phase: string;
        };
        /** ResearchRunPageDto */
        ResearchRunPageDto: {
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor: string | null;
            /** Runs */
            runs: components["schemas"]["ResearchRunSummaryDto"][];
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchRunSummaryDto */
        ResearchRunSummaryDto: {
            /** Admission Resolution Fingerprint */
            admission_resolution_fingerprint: string;
            /** Artifact Ref */
            artifact_ref: string | null;
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            failure: components["schemas"]["ResearchRunFailureDto"] | null;
            /** Finished At */
            finished_at: string | null;
            /** Queued At */
            queued_at: string;
            /** Result Ref */
            result_ref: string | null;
            /** Revision */
            revision: string;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Specification Fingerprint */
            specification_fingerprint: string;
            /** Specification Schema Version */
            specification_schema_version: number;
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
        };
        /** ResearchScalarDto */
        ResearchScalarDto: {
            /**
             * Type
             * @enum {string}
             */
            type: "NULL" | "BOOLEAN" | "INTEGER" | "DECIMAL" | "STRING";
            /** Value */
            value: boolean | number | string | null;
        };
        /** ResearchScientificSeriesPageDto */
        ResearchScientificSeriesPageDto: {
            /** Has More */
            has_more: boolean;
            /** Next After Ts Event Ns */
            next_after_ts_event_ns: string | null;
            /** Points */
            points: (components["schemas"]["ResearchMarketPointDto"] | components["schemas"]["ResearchVariablePointDto"] | components["schemas"]["ResearchSignalPointDto"])[];
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /** ResearchSeriesReferenceDto */
        ResearchSeriesReferenceDto: {
            /** Calculation Fingerprint */
            calculation_fingerprint: string;
            /** Node Fingerprint */
            node_fingerprint: string;
            /** Output Name */
            output_name: string;
        };
        /** ResearchSignalPointDto */
        ResearchSignalPointDto: {
            /** Instrument Id */
            instrument_id: string;
            /** Ts Event Ns */
            ts_event_ns: string;
            /** Value */
            value: boolean | null;
        };
        /** ResearchSignalsDto */
        ResearchSignalsDto: {
            /** Entry */
            entry: (components["schemas"]["ResearchComparisonDto"] | components["schemas"]["ResearchNotDto"] | components["schemas"]["ResearchAndDto"] | components["schemas"]["ResearchOrDto"]) | null;
            /** Exit */
            exit: (components["schemas"]["ResearchComparisonDto"] | components["schemas"]["ResearchNotDto"] | components["schemas"]["ResearchAndDto"] | components["schemas"]["ResearchOrDto"]) | null;
        };
        /** ResearchStatisticPointDto */
        ResearchStatisticPointDto: {
            /** Sample Count */
            sample_count: number;
            /** Statistic Value */
            statistic_value: string | null;
            /** Status */
            status: string;
            /** Ts Event Ns */
            ts_event_ns: string;
        };
        /** ResearchStatisticSeriesPageDto */
        ResearchStatisticSeriesPageDto: {
            /** Has More */
            has_more: boolean;
            /** Next After Ts Event Ns */
            next_after_ts_event_ns: string | null;
            /** Points */
            points: components["schemas"]["ResearchStatisticPointDto"][];
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Statistics Fingerprint */
            statistics_fingerprint: string;
        };
        /** ResearchStatisticsCapabilityCatalogDto */
        ResearchStatisticsCapabilityCatalogDto: {
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Statistics */
            statistics: components["schemas"]["ResearchStatisticsCapabilityDto"][];
        };
        /** ResearchStatisticsCapabilityDto */
        ResearchStatisticsCapabilityDto: {
            /** Executable */
            executable: boolean;
            /** Statistic Type */
            statistic_type: string;
            /** Target Required */
            target_required: boolean;
            /** Target Semantic Roles */
            target_semantic_roles: string[];
            /** Variable Kinds */
            variable_kinds: string[];
            /** Variable Semantic Roles */
            variable_semantic_roles: string[];
        };
        /** ResearchStatisticsCatalogDto */
        ResearchStatisticsCatalogDto: {
            /** Research Result Fingerprint */
            research_result_fingerprint: string;
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Statistics */
            statistics: components["schemas"]["ResearchStatisticsDescriptorDto"][];
        };
        /** ResearchStatisticsDefinitionDto */
        ResearchStatisticsDefinitionDto: {
            /** Method */
            method: string;
            /** Minimum Observations */
            minimum_observations: number;
            numeric: components["schemas"]["ResearchNumericDefinitionDto"];
            /** Pairing Policy */
            pairing_policy: string;
            /** Rank Tie Method */
            rank_tie_method: string;
            /** Universe Policy */
            universe_policy: string;
            /** Weighting */
            weighting: string;
        };
        /** ResearchStatisticsDefinitionRequestDto */
        ResearchStatisticsDefinitionRequestDto: {
            method: components["schemas"]["OnlyResearchStatisticsMethod"];
            /** Minimum Observations */
            minimum_observations: number;
            numeric: components["schemas"]["ResearchStatisticsNumericDto"];
            pairing_policy: components["schemas"]["OnlyResearchPairingPolicy"];
            rank_tie_method: components["schemas"]["OnlyResearchRankTieMethod"];
            /** Schema Version */
            schema_version: number;
            universe_policy: components["schemas"]["OnlyResearchUniversePolicy"];
            weighting: components["schemas"]["OnlyResearchWeighting"];
        };
        /** ResearchStatisticsDescriptorDto */
        ResearchStatisticsDescriptorDto: {
            definition: components["schemas"]["ResearchStatisticsDefinitionDto"];
            feature: components["schemas"]["ResearchSeriesReferenceDto"];
            /** Result Content Fingerprint */
            result_content_fingerprint: string;
            /** Row Count */
            row_count: number;
            /** Statistics Fingerprint */
            statistics_fingerprint: string;
            /** Statistics Result Fingerprint */
            statistics_result_fingerprint: string;
            /** Statistics Result Schema Version */
            statistics_result_schema_version: number;
            target: components["schemas"]["ResearchSeriesReferenceDto"];
        };
        /** ResearchStatisticsNumericDto */
        ResearchStatisticsNumericDto: {
            /** Output Quantum */
            output_quantum: string;
            /** Precision */
            precision: number;
            /** Representation */
            representation: string;
            /** Rounding */
            rounding: string;
        };
        /** ResearchStatisticsRequestDto */
        ResearchStatisticsRequestDto: {
            definition: components["schemas"]["ResearchStatisticsDefinitionRequestDto"];
            /** Target Instance Key */
            target_instance_key: string;
            variable: components["schemas"]["ResearchVariableRefDto"];
        };
        /** ResearchSweepParameterDto */
        ResearchSweepParameterDto: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "SWEEP";
            /** Values */
            values: components["schemas"]["ResearchScalarDto"][];
        };
        /** ResearchTypedLiteralDto */
        ResearchTypedLiteralDto: {
            data_type: components["schemas"]["OnlyCalculationDataType"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "LITERAL";
            value: components["schemas"]["ResearchScalarDto"];
        };
        /** ResearchUniverseCatalogDto */
        ResearchUniverseCatalogDto: {
            /** Registered Universes */
            registered_universes: components["schemas"]["ResearchRegisteredUniverseDto"][];
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Selection Kinds */
            selection_kinds: string[];
        };
        /** ResearchUniverseSelectionDto */
        ResearchUniverseSelectionDto: {
            /** Instrument Ids */
            instrument_ids: string[];
            kind: components["schemas"]["OnlyResearchUniverseKind"];
            /** Registered Id */
            registered_id: string | null;
        };
        /** ResearchVariablePointDto */
        ResearchVariablePointDto: {
            /** Boolean Value */
            boolean_value: boolean | null;
            /** Decimal Value */
            decimal_value: string | null;
            /** Instrument Id */
            instrument_id: string;
            /** Integer Value */
            integer_value: string | null;
            /** String Value */
            string_value: string | null;
            /** Ts Event Ns */
            ts_event_ns: string;
            /** Value Kind */
            value_kind: string;
        };
        /** ResearchVariableRefDto */
        ResearchVariableRefDto: {
            /** Instance Key */
            instance_key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "VARIABLE";
            /** Output Name */
            output_name: string;
        };
        /** SubmitResearchRunRequest */
        SubmitResearchRunRequest: {
            /** Specification */
            specification: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** SubmitResearchRunResponse */
        SubmitResearchRunResponse: {
            run: components["schemas"]["ResearchRunDto"];
            /** Submission Disposition */
            submission_disposition: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifact_summary_api_v2_research_artifacts__research_result_fingerprint__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_result_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchArtifactSummaryDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    candidate_catalog_api_v2_research_artifacts__research_result_fingerprint__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_result_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCandidateCatalogDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    candidate_graph_api_v2_research_artifacts__research_result_fingerprint__candidates__candidate_fingerprint__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_result_fingerprint: string;
                candidate_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCandidateGraphDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    market_series_api_v2_research_artifacts__research_result_fingerprint__market_series_get: {
        parameters: {
            query: {
                instrument_id: string;
                from_ts_event_ns?: string | null;
                to_ts_event_ns?: string | null;
                after_ts_event_ns?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                research_result_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchScientificSeriesPageDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    signal_series_api_v2_research_artifacts__research_result_fingerprint__signals__candidate_fingerprint___role__series_get: {
        parameters: {
            query: {
                instrument_id: string;
                from_ts_event_ns?: string | null;
                to_ts_event_ns?: string | null;
                after_ts_event_ns?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                research_result_fingerprint: string;
                candidate_fingerprint: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchScientificSeriesPageDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    statistics_catalog_api_v2_research_artifacts__research_result_fingerprint__statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_result_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchStatisticsCatalogDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    statistic_series_api_v2_research_artifacts__research_result_fingerprint__statistics__statistics_fingerprint__series_get: {
        parameters: {
            query?: {
                from_ts_event_ns?: string | null;
                to_ts_event_ns?: string | null;
                after_ts_event_ns?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                research_result_fingerprint: string;
                statistics_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchStatisticSeriesPageDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    variable_catalog_api_v2_research_artifacts__research_result_fingerprint__variables_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_result_fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchPublishedSeriesCatalogDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    variable_series_api_v2_research_artifacts__research_result_fingerprint__variables__calculation_fingerprint___node_fingerprint___output_name__series_get: {
        parameters: {
            query: {
                instrument_id: string;
                candidate_fingerprint?: string | null;
                from_ts_event_ns?: string | null;
                to_ts_event_ns?: string | null;
                after_ts_event_ns?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                research_result_fingerprint: string;
                calculation_fingerprint: string;
                node_fingerprint: string;
                output_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchScientificSeriesPageDto"];
                };
            };
            /** @description Invalid Research query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Exact Artifact or Statistics identity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Scientific evidence is unavailable for this profile */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Research Artifact verification failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchErrorDto"];
                };
            };
        };
    };
    calculations_api_v2_research_catalog_calculations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCalculationCatalogDto"];
                };
            };
        };
    };
    dataset_fields_api_v2_research_catalog_dataset_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchDatasetFieldCatalogDto"];
                };
            };
        };
    };
    statistics_api_v2_research_catalog_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchStatisticsCapabilityCatalogDto"];
                };
            };
        };
    };
    universes_api_v2_research_catalog_universes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchUniverseCatalogDto"];
                };
            };
        };
    };
    resolve_definition_api_v2_research_definitions_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchDefinitionRequestDto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchDefinitionResolutionDto"];
                };
            };
            /** @description Invalid Research Definition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchDefinitionErrorEnvelopeDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v2_research_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunPageDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
        };
    };
    submit_run_api_v2_research_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitResearchRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResearchRunResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
        };
    };
    get_run_api_v2_research_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
        };
    };
    cancel_run_api_v2_research_runs__run_id__cancellation_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunErrorEnvelopeDto"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchHealthDto"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchHealthDto"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchHealthDto"];
                };
            };
        };
    };
}
